name: authhub
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  local_auth: ^0.4.0+1
  flutter_secure_storage: ^3.2.1+1
  password_strength: ^0.1.2


  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.0

  sqflite: any

  encrypt:
  path_provider: ^1.1.0
  shared_preferences: ^0.5.2+1
  flutter_material_color_picker: ^1.0.0
  logging: ^0.11.4
  logging_appenders: ^0.4.2+3
  autofill_service:
    path: ../autofill_service-master





dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true

  assets:
    - assets/key.png

